### ISSUE TITLE
Return series ID in issue

### ISSUE THREAD

**Issue by rad96** [Metron-Project/mokkari#66]
When retrieving issue this two values can not define series, because they are not determined
![изображение](https://github.com/user-attachments/assets/8d145425-a7fd-4106-942a-b1f42add0653)

Why not return series id?

**Comment by bpepple** [comment]
What do you mean by not defined? If I remember correctly,  both year_began and volume are required fields.

**Comment by rad96** [comment]
By not determined I meant they can be changed without a problem

**Comment by bpepple** [comment]
This response provides a list of issues, and the information is typically displayed to the end-user to help identify the issue they're looking for.

Most end-users will not know or care about the series id. Now, the developer writing the software, consuming the response, can use the series id as a parameter to filter the results, but I don't see how it would be of any use to the end-user.
